### ISSUE TITLE
Deprecate project and package in favor of main SQL sink

### ISSUE THREAD

**Issue by MV10** [aaxelm/serilog-sinks-mssqlservercore#14]
@aaxelm --

This is a request to change the README to indicate this package is deprecated and no longer maintained, and to direct people to use the main _Serilog.Sinks.MSSqlServer_ package now that it has full .NET Standard support.

We are regularly seeing issues opened in that sink by users who are actually using this older package. It is especially confusing because the project URL for this package points to that repository instead of this one.

Therefore, it would also be helpful if a new package was released with a description clarifying the deprecated status of this package and perhaps correcting the project URL.

**Comment by alex-munteanu** [comment]
Modified the readme file to specify this project is deprecated, linking to the official project.

Also modified NuGet package to have correct project URL and to specify it is deprecated.

**Comment by MV10** [comment]
Greatly appreciated!
