### ISSUE TITLE
Error message : The given key was not present in the dictionary when adding new column

### ISSUE THREAD

**Issue by sebastien0099** [aaxelm/serilog-sinks-mssqlservercore#2]
Hi Alexandru,

I'm trying to execute the following code. I added a new column in my Logs table. And I keep getting the same error message : Unable to write 1 log events to the database due to following error: The given key was not present in the dictionary. If I remove the additional column then It works and logs get saved in my Logs table. Any idea what I'm doing wrong ? 

![image](https://cloud.githubusercontent.com/assets/11855462/23096451/e87c4f96-f61c-11e6-9ff1-2e630651ab65.png)

![image](https://cloud.githubusercontent.com/assets/11855462/23096428/84095860-f61c-11e6-87a3-eb0e1e848012.png)

Here is my project.json:
`"Serilog": "2.4.0", "Serilog.Extensions.Logging": "1.4.0", "Serilog.Sinks.ColoredConsole": "2.0.0", "Serilog.Sinks.MSSqlServerCore": "1.0.0", "Serilog.Sinks.Email": "2.2.0"`

And here my startup class:
`Serilog.Debugging.SelfLog.Enable(Console.Out);

            var columnOptions = new ColumnOptions();
            columnOptions.Store.Add(StandardColumn.LogEvent);
            columnOptions.LogEvent.ExcludeAdditionalProperties = false;
            columnOptions.AdditionalDataColumns = new Collection<DataColumn>
            {
                new DataColumn { DataType = typeof(string), ColumnName = "MyNewColumn"}
           };

            Serilog.Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .WriteTo.ColoredConsole()
                 .WriteTo.MSSqlServer(Configuration["Data:ConnectionString"], "Logs", columnOptions: columnOptions)
                .CreateLogger();

            
            Serilog.ILogger ctx = Serilog.Log.Logger.ForContext("MyNewColumn", "123456");
            Serilog.Log.Warning("Hello, world!", ctx);

            `

**Comment by alex-munteanu** [comment]
Hi Sebastien,

Sorry it took me a while to inspect this. It seems that if you do this:

`Serilog.Log.ForContext("MyNewColumn", "123456").Warning("Hello, world!");`

instead of this:

`Serilog.ILogger ctx = Serilog.Log.Logger.ForContext("MyNewColumn", "123456");
 Serilog.Log.Warning("Hello, world!", ctx);`

everything works fine.

**Comment by sebastien0099** [comment]
Hi Alexandru,

Thanks a lot, it was my mistake and it works fine from the startup page. I found the way to use this from an MVC controller as well using Dependency Injection. 

Sebastien
