### ISSUE TITLE
.NETStandard

### ISSUE THREAD

**Issue by Megasware128** [aaxelm/serilog-sinks-mssqlservercore#3]
Is .NETStandard 1.6 really necessary? System.Data.SqlClient should work already in .NETStandard 1.2 or at least 1.3. EntityFrameworkCore implemented 1.3. This library would be more useful to me if it didn't have such a high requirement. I do have to say great work for making a port. 👍

**Comment by alex-munteanu** [comment]
Published the new version that should work with .NETStandard 1.2 or later:
https://www.nuget.org/packages/Serilog.Sinks.MSSqlServerCore/1.1.0
